[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "api"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[template.environment]
  ABLY_API_KEY = "change me to your Ably API key"

 [[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
